# Generated by Django 4.0.2 on 2022-02-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='total',
            new_name='total_amount',
        ),
    ]
