# Generated by Django 4.0.2 on 2022-02-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_receipt_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='receipt',
            new_name='receipt_1',
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_10',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_2',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_3',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_4',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_5',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_6',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_7',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_8',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_9',
            field=models.FileField(blank=True, null=True, upload_to='receipts'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created',
            field=models.DateField(default='2022-02-25'),
        ),
    ]
