# Generated by Django 3.0.6 on 2022-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=20)),
                ('total_amount', models.PositiveIntegerField()),
                ('created', models.DateField(default='2022-02-26')),
                ('receipt_1', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_2', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_3', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_4', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_5', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_6', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_7', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_8', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_9', models.FileField(blank=True, null=True, upload_to='receipts')),
                ('receipt_10', models.FileField(blank=True, null=True, upload_to='receipts')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
