# Generated by Django 3.0.6 on 2022-02-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_receipt', '0004_rename_receipt_receipt_receipt_1_receipt_receipt_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='created',
            field=models.DateField(default='2022-02-26'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
