# Generated by Django 4.0.2 on 2022-02-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=240)),
                ('phone', models.CharField(max_length=20)),
                ('total', models.PositiveIntegerField()),
                ('created', models.DateField(default='2022-02-24')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
